### PR TITLE
Bug 1163631 - Make master/minion playbook configurable in cluster.sh

### PR DESCRIPTION
**Pull request by pravisankar**
Now config options can take both short and long notations.

### CODE REVIEW

**Comment by pravisankar** [comment]
@jwhonce review/merge

**Comment by jwhonce** [comment]
@pravisankar LGTM just need to rebase

**Comment by pravisankar** [comment]
[merge]

**Comment by pravisankar** [comment]
@jwhonce rebase done, please merge the pr

**Pull request merged**
